/** Store catalog + assistant knowledge base.
 *  In the real integration this data comes from Shopify; for the demo we
 *  keep it here so the assistant answers from "store data", not guesses. */

export type Product = {
  id: string;
  name: string;
  price: number;
  blurb: string;
  image: string;
  tag?: string;
};

export const PRODUCTS: Product[] = [
  {
    id: "iphone-15",
    name: "iPhone 15",
    price: 699,
    blurb: "A vibrant 6.1-inch iPhone with the A16 Bionic chip, Dynamic Island, and a versatile dual-camera system.",
    image: "",
    tag: "Popular",
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    price: 899,
    blurb: "Built with a titanium design and powered by the A17 Pro chip, delivering flagship performance in a compact form.",
    image: "",
    tag: "Pro",
  },
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    price: 999,
    blurb: "The ultimate iPhone 15 experience with a 6.7-inch display, A17 Pro chip, and advanced 5x Telephoto camera.",
    image: "",
    tag: "Flagship",
  },
  {
    id: "iphone-14",
    name: "iPhone 14",
    price: 499,
    blurb: "A dependable 6.1-inch iPhone featuring the A15 Bionic chip, OLED display, and dual-camera system.",
    image: "",
  },
  {
    id: "iphone-14-plus",
    name: "iPhone 14 Plus",
    price: 599,
    blurb: "Enjoy a larger 6.7-inch Super Retina XDR display with all-day battery life and the powerful A15 Bionic chip.",
    image: "",
  },
  {
    id: "iphone-se-3rd-gen",
    name: "iPhone SE (3rd Gen)",
    price: 349,
    blurb: "A compact iPhone with the familiar Home button, A15 Bionic performance, 5G connectivity, and a single 12MP camera.",
    image: "",
    tag: "Best value",
  },
  {
    id: "iphone-15-plus",
    name: "iPhone 15 Plus",
    price: 799,
    blurb: "A spacious 6.7-inch display meets A16 Bionic performance, Dynamic Island, and a powerful dual-camera system.",
    image: "",
  },
  {
    id: "iphone-15-pro-256gb",
    name: "iPhone 15 Pro 256GB",
    price: 949,
    blurb: "A premium titanium iPhone designed for demanding users, with A17 Pro performance and a professional-grade camera system.",
    image: "",
    tag: "Pro",
  },
  {
    id: "iphone-15-pro-max-512gb",
    name: "iPhone 15 Pro Max 512GB",
    price: 1149,
    blurb: "Go further with the large Pro Max display, A17 Pro chip, advanced cameras, and generous 512GB storage.",
    image: "",
    tag: "Premium",
  },
  {
    id: "silicone-case-with-magsafe",
    name: "Silicone Case with MagSafe",
    price: 49,
    blurb: "A soft-touch silicone case with built-in MagSafe magnets for reliable protection and effortless wireless charging.",
    image: "",
    tag: "Accessory",
  },
  {
    id: "clear-case-with-magsafe",
    name: "Clear Case with MagSafe",
    price: 49,
    blurb: "Show off your iPhone's original finish while adding everyday protection and seamless MagSafe compatibility.",
    image: "",
    tag: "Accessory",
  },
  {
    id: "20w-usb-c-power-adapter",
    name: "20W USB-C Power Adapter",
    price: 19,
    blurb: "A compact 20W USB-C power adapter for fast, efficient charging for iPhone and other compatible Apple devices.",
    image: "",
    tag: "Accessory",
  },
  {
    id: "usb-c-to-lightning-cable",
    name: "USB-C to Lightning Cable",
    price: 19,
    blurb: "A durable cable for charging and syncing Lightning-equipped iPhones and accessories with USB-C power adapters.",
    image: "",
    tag: "Accessory",
  },
  {
    id: "airpods-3rd-generation",
    name: "AirPods (3rd Generation)",
    price: 169,
    blurb: "Enjoy spatial audio, sweat and water resistance, and effortless pairing in a compact wireless earbud design.",
    image: "",
    tag: "Audio",
  },
  {
    id: "airpods-pro-2nd-generation",
    name: "AirPods Pro (2nd Generation)",
    price: 249,
    blurb: "Active Noise Cancellation, Adaptive Transparency, and a customizable fit make AirPods Pro ideal for immersive listening.",
    image: "",
    tag: "Audio",
  },
];

/** Product questions the assistant can answer from catalog data. */
export const PRODUCT_FACTS: Record<
  string,
  { match: RegExp; name: string; answer: string }
> = {
  iphone: {
    match: /\b(iphone|phone)\b/i,
    name: "iPhone lineup",
    answer:
      "We carry iPhone 15 ($699), iPhone 15 Pro ($899), iPhone 15 Pro Max ($999), iPhone 15 Plus ($799), iPhone 14 ($499), iPhone 14 Plus ($599), and iPhone SE 3rd Gen ($349). Each comes in multiple colors and storage options. All are brand-new genuine Apple products.",
  },
  iphone15: {
    match: /iphone 15(?!\s*(pro|plus))/i,
    name: "iPhone 15",
    answer:
      "The iPhone 15 features a 6.1-inch Super Retina XDR display, A16 Bionic chip, Dynamic Island, and a 48MP dual-camera system. It starts at $699 and comes in Black, Blue, and Green with 128GB, 256GB, or 512GB storage.",
  },
  iphone15pro: {
    match: /iphone 15 pro(?!\s*max)/i,
    name: "iPhone 15 Pro",
    answer:
      "The iPhone 15 Pro features a titanium design, A17 Pro chip, 6.1-inch Super Retina XDR display with ProMotion, and a pro camera system with 5x optical zoom. It starts at $899 and comes in Black Titanium, Blue Titanium, and Natural Titanium with 128GB, 256GB, or 512GB storage.",
  },
  iphone15promax: {
    match: /iphone 15 pro max/i,
    name: "iPhone 15 Pro Max",
    answer:
      "The iPhone 15 Pro Max has a 6.7-inch display, A17 Pro chip, and advanced 5x Telephoto camera. It starts at $999 and comes in Black Titanium, Natural Titanium, and White Titanium with 256GB, 512GB, or 1TB storage.",
  },
  iphone14: {
    match: /iphone 14(?!\s*plus)/i,
    name: "iPhone 14",
    answer:
      "The iPhone 14 features a 6.1-inch OLED display, A15 Bionic chip, and dual-camera system. It starts at $499 and comes in Midnight, Blue, and Purple with 128GB, 256GB, or 512GB storage.",
  },
  iphone14plus: {
    match: /iphone 14 plus/i,
    name: "iPhone 14 Plus",
    answer:
      "The iPhone 14 Plus has a larger 6.7-inch Super Retina XDR display with all-day battery life and the A15 Bionic chip. It starts at $599 in Midnight, Blue, and Starlight with 128GB, 256GB, or 512GB storage.",
  },
  iphonese: {
    match: /\b(iphone se|se 3rd|se third|budget iphone|cheapest iphone)\b/i,
    name: "iPhone SE (3rd Gen)",
    answer:
      "The iPhone SE (3rd Gen) features the familiar Home button with Touch ID, A15 Bionic chip, 5G connectivity, and a 12MP camera. At $349 it's our best-value iPhone, available in Midnight, Starlight, and Product Red with 64GB, 128GB, or 256GB storage.",
  },
  airpods: {
    match: /\b(airpod|earbud|earphone|headphone)\b/i,
    name: "AirPods",
    answer:
      "We carry AirPods 3rd Generation ($169) with spatial audio and sweat/water resistance, and AirPods Pro 2nd Generation ($249) with Active Noise Cancellation, Adaptive Transparency, and a customizable fit. Both pair effortlessly with any Apple device.",
  },
  accessories: {
    match: /\b(case|magsafe|charger|adapter|cable|lightning|usb-c|accessor)\b/i,
    name: "Accessories",
    answer:
      "We stock Silicone Case with MagSafe ($49, in Black/Storm Blue/Winter Blue), Clear Case with MagSafe ($49), 20W USB-C Power Adapter ($19), and USB-C to Lightning Cable ($19). All are genuine Apple accessories compatible with our full iPhone lineup.",
  },
};

export const POLICIES = {
  shipping:
    "Orders are processed within 1–2 business days. Domestic Standard Shipping is $9.99 (3–5 business days), Express is $19.99 (1–2 business days). Orders over $500 qualify for free Standard Shipping. International Standard is $29.99 (7–14 days), Express is $59.99 (3–7 days). International customers are responsible for customs duties and import taxes.",
  returns:
    "You can request a return within 14 calendar days of receiving your order. Items must be in original condition with all accessories and packaging — Apple ID signed out and Find My iPhone disabled. Refunds are issued to the original payment method within 5–7 business days after inspection. Customers pay return shipping for unwanted items; we cover it for defective, damaged, or incorrectly shipped products.",
};

/** Sample orders used to seed the demo database (from Customer_Orders.csv). */
export const SEED_ORDERS = [
  {
    orderNumber: "#10234",
    status: "processing",
    statusLabel: "Processing",
    carrier: null,
    tracking: null,
    eta: "Ships within 1–2 business days",
    placedAt: "Aug 16, 2026",
    items: [{ name: "iPhone 15 Pro 256GB - Natural Titanium", qty: 1 }],
    total: "$949.00",
    customerEmail: "daniel.mitchell@sample.shop",
  },
  {
    orderNumber: "#10235",
    status: "in_transit",
    statusLabel: "Shipped",
    carrier: "UPS",
    tracking: "1Z8A45W90372846125",
    eta: "Aug 20–22",
    placedAt: "Aug 15, 2026",
    items: [{ name: "iPhone 15 - Blue 128GB", qty: 1 }],
    total: "$699.00",
    customerEmail: "aisha.rahman@sample.shop",
  },
  {
    orderNumber: "#10236",
    status: "delivered",
    statusLabel: "Delivered",
    carrier: "USPS",
    tracking: "9400111899223857216847",
    eta: "Delivered Aug 19",
    placedAt: "Aug 14, 2026",
    items: [{ name: "iPhone 15 Pro Max 512GB - Black Titanium", qty: 1 }],
    total: "$1,149.00",
    customerEmail: "liam.oconnor@sample.shop",
  },
  {
    orderNumber: "#10237",
    status: "processing",
    statusLabel: "Processing",
    carrier: null,
    tracking: null,
    eta: "Ships within 1–2 business days",
    placedAt: "Aug 13, 2026",
    items: [{ name: "iPhone 14 256GB - Purple", qty: 1 }],
    total: "$499.00",
    customerEmail: "sofia.martinez@sample.shop",
  },
  {
    orderNumber: "#10238",
    status: "in_transit",
    statusLabel: "Shipped",
    carrier: "USPS",
    tracking: "9400111899223857216932",
    eta: "Aug 17–19",
    placedAt: "Aug 12, 2026",
    items: [
      { name: "AirPods Pro 2nd Generation - USB-C", qty: 1 },
      { name: "Silicone Case with MagSafe - Black", qty: 1 },
    ],
    total: "$298.00",
    customerEmail: "hiroshi.tanaka@sample.shop",
  },
  {
    orderNumber: "#10239",
    status: "delivered",
    statusLabel: "Delivered",
    carrier: "UPS",
    tracking: "1Z8A45W90372847561",
    eta: "Delivered Aug 16",
    placedAt: "Aug 11, 2026",
    items: [{ name: "iPhone 15 Plus 128GB - Pink", qty: 1 }],
    total: "$799.00",
    customerEmail: "amelia.thompson@sample.shop",
  },
  {
    orderNumber: "#10240",
    status: "in_transit",
    statusLabel: "Delayed",
    carrier: "USPS",
    tracking: "9400111899223857217058",
    eta: "Delayed — updated estimate Aug 19",
    placedAt: "Aug 10, 2026",
    items: [{ name: "iPhone 15 Pro 512GB - Blue Titanium", qty: 1 }],
    total: "$899.00",
    customerEmail: "omar.alhassan@sample.shop",
  },
  {
    orderNumber: "#10241",
    status: "delivered",
    statusLabel: "Delivered",
    carrier: "UPS",
    tracking: "1Z8A45W90372848934",
    eta: "Delivered Aug 13",
    placedAt: "Aug 8, 2026",
    items: [{ name: "iPhone SE 128GB - Starlight", qty: 1 }],
    total: "$349.00",
    customerEmail: "emily.carter@sample.shop",
  },
  {
    orderNumber: "#10242",
    status: "in_transit",
    statusLabel: "Shipped",
    carrier: "USPS",
    tracking: "9400111899223857217196",
    eta: "Aug 12–14",
    placedAt: "Aug 7, 2026",
    items: [{ name: "iPhone 15 256GB - Green", qty: 1 }],
    total: "$699.00",
    customerEmail: "lucas.ferreira@sample.shop",
  },
  {
    orderNumber: "#10243",
    status: "processing",
    statusLabel: "Processing",
    carrier: null,
    tracking: null,
    eta: "Ships within 1–2 business days",
    placedAt: "Aug 5, 2026",
    items: [{ name: "iPhone 14 Plus 128GB - Midnight", qty: 1 }],
    total: "$599.00",
    customerEmail: "noor.fatima@sample.shop",
  },
  {
    orderNumber: "#10244",
    status: "delivered",
    statusLabel: "Delivered",
    carrier: "UPS",
    tracking: "1Z8A45W90372849382",
    eta: "Delivered Aug 9",
    placedAt: "Aug 4, 2026",
    items: [{ name: "iPhone 15 Pro Max 256GB - Natural Titanium", qty: 1 }],
    total: "$999.00",
    customerEmail: "alexander.petrov@sample.shop",
  },
  {
    orderNumber: "#10245",
    status: "in_transit",
    statusLabel: "Shipped",
    carrier: "USPS",
    tracking: "9400111899223857217340",
    eta: "Aug 7–9",
    placedAt: "Aug 2, 2026",
    items: [
      { name: "iPhone 15 128GB - Black", qty: 1 },
      { name: "20W USB-C Power Adapter", qty: 1 },
    ],
    total: "$718.00",
    customerEmail: "grace.kim@sample.shop",
  },
  {
    orderNumber: "#10246",
    status: "delivered",
    statusLabel: "Delivered",
    carrier: "UPS",
    tracking: "1Z8A45W90372850817",
    eta: "Delivered Aug 6",
    placedAt: "Aug 1, 2026",
    items: [{ name: "iPhone 14 512GB - Starlight", qty: 1 }],
    total: "$499.00",
    customerEmail: "yusuf.demir@sample.shop",
  },
  {
    orderNumber: "#10247",
    status: "in_transit",
    statusLabel: "Delayed",
    carrier: "USPS",
    tracking: "9400111899223857217485",
    eta: "Delayed — updated estimate Aug 8",
    placedAt: "Jul 30, 2026",
    items: [{ name: "iPhone 15 Pro 256GB - White Titanium", qty: 1 }],
    total: "$949.00",
    customerEmail: "chloe.williams@sample.shop",
  },
  {
    orderNumber: "#10248",
    status: "delivered",
    statusLabel: "Delivered",
    carrier: "UPS",
    tracking: "1Z8A45W90372851642",
    eta: "Delivered Aug 2",
    placedAt: "Jul 28, 2026",
    items: [
      { name: "iPhone 15 Pro Max 512GB - Blue Titanium", qty: 1 },
      { name: "Clear Case with MagSafe", qty: 1 },
    ],
    total: "$1,198.00",
    customerEmail: "rohan.mehta@sample.shop",
  },
  {
    orderNumber: "#10249",
    status: "in_transit",
    statusLabel: "Shipped",
    carrier: "USPS",
    tracking: "9400111899223857217539",
    eta: "Jul 31 – Aug 2",
    placedAt: "Jul 26, 2026",
    items: [{ name: "iPhone 15 Plus 256GB - Yellow", qty: 1 }],
    total: "$799.00",
    customerEmail: "elena.rossi@sample.shop",
  },
  {
    orderNumber: "#10250",
    status: "processing",
    statusLabel: "Processing",
    carrier: null,
    tracking: null,
    eta: "Ships within 1–2 business days",
    placedAt: "Jul 24, 2026",
    items: [{ name: "iPhone 15 128GB - Pink", qty: 1 }],
    total: "$699.00",
    customerEmail: "marcus.johnson@sample.shop",
  },
  {
    orderNumber: "#10251",
    status: "delivered",
    statusLabel: "Delivered",
    carrier: "UPS",
    tracking: "1Z8A45W90372852976",
    eta: "Delivered Jul 27",
    placedAt: "Jul 22, 2026",
    items: [
      { name: "iPhone 15 Pro 512GB - Natural Titanium", qty: 1 },
      { name: "AirPods 3rd Generation", qty: 1 },
    ],
    total: "$1,068.00",
    customerEmail: "leila.haddad@sample.shop",
  },
  {
    orderNumber: "#10252",
    status: "in_transit",
    statusLabel: "Shipped",
    carrier: "USPS",
    tracking: "9400111899223857217681",
    eta: "Jul 25–27",
    placedAt: "Jul 20, 2026",
    items: [
      { name: "iPhone 14 128GB - Midnight", qty: 1 },
      { name: "USB-C to Lightning Cable", qty: 1 },
    ],
    total: "$518.00",
    customerEmail: "oliver.smith@sample.shop",
  },
  {
    orderNumber: "#10253",
    status: "delivered",
    statusLabel: "Delivered",
    carrier: "USPS",
    tracking: "1Z8A45W90372853425",
    eta: "Delivered Jul 23",
    placedAt: "Jul 18, 2026",
    items: [{ name: "iPhone SE 256GB - Product Red", qty: 1 }],
    total: "$349.00",
    customerEmail: "mei.lin@sample.shop",
  },
] as const;
